-- ============================================================================
-- V001: Create sys_tenant table
-- ============================================================================
-- Description: Core tenant table for multi-tenancy support.
--              This is a system-level table (no tenant_id column).
--              
-- Architecture Layer: Layer 2C - Platform Commons (platform-tenant module)
-- 
-- Design Notes:
-- - Uses BIGINT IDs generated by Snowflake algorithm
-- - Status uses VARCHAR to store enum values for flexibility
-- - Code is unique business identifier for tenant (e.g., subdomain prefix)
-- - Timestamps use TIMESTAMPTZ for timezone-aware storage
--
-- Constraints:
-- - Primary key on id (Snowflake generated)
-- - Unique constraint on code (natural key for tenant lookup)
-- - Status must match TenantStatus enum values
--
-- Related Tables:
-- - sys_tenant_member: Links identities to tenants
-- - sys_organization: Organizational structure within tenant
--
-- @since 3.1.0
-- @author Brix Platform Team
-- ============================================================================

-- Create sys_tenant table
CREATE TABLE IF NOT EXISTS sys_tenant (
    -- Primary key: Snowflake-generated unique identifier
    id              BIGINT          PRIMARY KEY,
    
    -- Business identifier: unique code for tenant (e.g., subdomain)
    -- Used for URL routing, API access, and external integrations
    code            VARCHAR(64)     NOT NULL,
    
    -- Display name: human-readable tenant name
    name            VARCHAR(256)    NOT NULL,
    
    -- Tenant lifecycle status
    -- Valid values: PENDING_ACTIVATION, ACTIVE, SUSPENDED, TERMINATED
    -- @see io.brix.platform.tenant.enums.TenantStatus
    status          VARCHAR(32)     NOT NULL DEFAULT 'PENDING_ACTIVATION',
    
    -- Audit timestamps
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ,
    
    -- Unique constraint on tenant code
    -- Ensures no duplicate codes for tenant identification
    CONSTRAINT uk_sys_tenant_code UNIQUE (code)
);

-- Index for status-based queries (monitoring, reporting)
CREATE INDEX IF NOT EXISTS idx_sys_tenant_status 
    ON sys_tenant(status);

-- Index for creation time (sorting, pagination)
CREATE INDEX IF NOT EXISTS idx_sys_tenant_created_at 
    ON sys_tenant(created_at DESC);

-- Comments for documentation
COMMENT ON TABLE sys_tenant IS 'Core tenant table for multi-tenancy. System-level table without tenant_id.';
COMMENT ON COLUMN sys_tenant.id IS 'Primary key (Snowflake ID)';
COMMENT ON COLUMN sys_tenant.code IS 'Unique business identifier for tenant (e.g., subdomain prefix)';
COMMENT ON COLUMN sys_tenant.name IS 'Human-readable display name';
COMMENT ON COLUMN sys_tenant.status IS 'Tenant lifecycle status (TenantStatus enum)';
COMMENT ON COLUMN sys_tenant.created_at IS 'Record creation timestamp';
COMMENT ON COLUMN sys_tenant.updated_at IS 'Last update timestamp';
