/**
 * Copyright 2026 Brix Platform Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 * @file react-router Router Adapter
 * @description Encapsulates react-router-dom to provide routing capabilities for the Host layer
 * @module @brix-sdk/infra-adapter-router-web/ReactRouterAdapter
 * @version 3.0.0
 * 
 * [Design Notes]
 * ReactRouterAdapter is the encapsulation layer for react-router-dom.
 * It provides routing capabilities to the Host layer and is the underlying dependency for NavigationCapability implementation.
 * 
 * [Architectural Position]
 * ```
 * ������������������������������������������������������������������������������
 * ��  Plugin Layer                       ��
 * ��  Uses NavigationCapability          ��
 * ��  ? MUST NOT use react-router directly��
 * ���������������������������������Щ�������������������������������������������
 *                 �� Request navigation
 * ������������������������������������������������������������������������������
 * ��  platform-navigation-web            ��
 * ��  NavigationCapabilityImpl           ��
 * ���������������������������������Щ�������������������������������������������
 *                 �� Calls
 * ������������������������������������������������������������������������������
 * ��  infra-adapter-router-web           ��  �� This module
 * ��  ReactRouterAdapter                 ��
 * ���������������������������������Щ�������������������������������������������
 *                 �� Wraps
 * ������������������������������������������������������������������������������
 * ��  react-router-dom                   ��
 * ��  Infrastructure Library             ��
 * ������������������������������������������������������������������������������
 * ```
 * 
 * [v3.0 Architectural Constraint - Red Line 1]
 * - Plugins MUST NOT use react-router directly
 * - Plugins MUST NOT register routes (routes are assembled by Host from Manifest)
 * - Plugins use PageId instead of URL for navigation
 * 
 * [Technical Notes]
 * This module is not a publicly exposed API, but an internal implementation dependency of the Host layer.
 * Plugin developers should not use this module directly.
 */

import { 
  createBrowserRouter,
  createMemoryRouter,
  type RouteObject,
  type Location,
} from 'react-router-dom';
import type { ComponentType } from 'react';

// Router return type
type RouterInstance = ReturnType<typeof createBrowserRouter>;

/**
 * Page configuration (from Manifest parsing)
 */
export interface PageConfig {
  /** 
   * Page ID
   * 
   * Format: pluginId:pageName
   * @example "booking:list", "booking:detail"
   */
  readonly pageId: string;
  
  /**
   * URL Path
   * 
   * Generated by Host based on PageId, plugins should not be aware of this.
   * @example "/booking", "/booking/:id"
   */
  readonly path: string;
  
  /**
   * Page component
   */
  readonly component: ComponentType<unknown>;
  
  /**
   * Page title
   */
  readonly title?: string;
  
  /**
   * Whether authentication is required
   */
  readonly requireAuth?: boolean;
  
  /**
   * Required permissions
   */
  readonly permissions?: readonly string[];
  
  /**
   * Child pages
   */
  readonly children?: readonly PageConfig[];
}

/**
 * Navigation options
 */
export interface NavigateOptions {
  /** Whether to replace current history entry */
  replace?: boolean;
  /** Additional state */
  state?: unknown;
}

/**
 * Route change listener
 */
export type RouteChangeListener = (location: Location, action: 'PUSH' | 'POP' | 'REPLACE') => void;

/**
 * Router type
 */
export type RouterType = 'browser' | 'memory';

/**
 * ReactRouterAdapter configuration options
 */
export interface ReactRouterAdapterOptions {
  /**
   * Router type
   * 
   * - browser: Based on browser History API
   * - memory: In-memory based (SSR/testing)
   * 
   * @default 'browser'
   */
  type?: RouterType;
  
  /**
   * Base path
   * 
   * Application's base URL path prefix.
   * @example "/app"
   */
  basename?: string;
  
  /**
   * Initial routes (memory router only)
   */
  initialEntries?: string[];
}

/**
 * react-router Router Adapter
 * 
 * Encapsulates react-router-dom to provide routing capabilities for the Host layer.
 * 
 * [Core Features]
 * - Route registration: Generate route configuration from PageConfig list
 * - Navigation control: Provide programmatic navigation API
 * - State listening: Listen to route change events  
 * - PageId mapping: Maintain PageId to URL mapping
 * 
 * [Usage Example]
 * ```typescript
 * // Host layer usage (not plugin code)
 * const adapter = new ReactRouterAdapter({ basename: '/app' });
 * 
 * // Register pages (from Manifest parsing)
 * adapter.registerPages([
 *   { pageId: 'booking:list', path: '/booking', component: BookingList },
 *   { pageId: 'booking:detail', path: '/booking/:id', component: BookingDetail },
 * ]);
 * 
 * // Get router
 * const router = adapter.getRouter();
 * 
 * // Navigate to page
 * adapter.navigateToPage('booking:detail', { id: '123' });
 * ```
 */
export class ReactRouterAdapter {
  /** Configuration options */
  private readonly options: Required<ReactRouterAdapterOptions>;
  
  /** react-router instance */
  private router: RouterInstance | null = null;
  
  /** PageId to URL path mapping */
  private readonly pageIdToPath = new Map<string, string>();
  
  /** URL path to PageId mapping */
  private readonly pathToPageId = new Map<string, string>();
  
  /** Registered page configurations */
  private readonly registeredPages: PageConfig[] = [];
  
  /** Route change listeners */
  private readonly listeners = new Set<RouteChangeListener>();
  
  /**
   * Create ReactRouterAdapter instance
   * 
   * @param options - Configuration options
   */
  constructor(options: ReactRouterAdapterOptions = {}) {
    this.options = {
      type: options.type ?? 'browser',
      basename: options.basename ?? '',
      initialEntries: options.initialEntries ?? ['/'],
    };
  }
  
  /**
   * Register page configurations
   * 
   * Generate react-router route configuration from PageConfig list.
   * Should be called by the Host layer at application startup.
   * 
   * @param pages - Page configuration list
   */
  registerPages(pages: PageConfig[]): void {
    // Clear existing mappings
    this.pageIdToPath.clear();
    this.pathToPageId.clear();
    this.registeredPages.length = 0;
    
    // Build mapping relationships
    for (const page of pages) {
      this.addPageMapping(page);
    }
    
    // Generate route configuration
    const routes = this.buildRouteObjects(pages);
    
    // Create router
    this.router = this.createRouter(routes);
    
    // Set up route listening
    if (this.router) {
      this.router.subscribe((state: { location: Location; historyAction: string }) => {
        const action = state.historyAction as 'PUSH' | 'POP' | 'REPLACE';
        for (const listener of this.listeners) {
          listener(state.location, action);
        }
      });
    }
  }
  
  /**
   * Add page mapping
   */
  private addPageMapping(page: PageConfig): void {
    this.pageIdToPath.set(page.pageId, page.path);
    this.pathToPageId.set(page.path, page.pageId);
    this.registeredPages.push(page);
    
    // Recursively process child pages
    if (page.children) {
      for (const child of page.children) {
        this.addPageMapping(child);
      }
    }
  }
  
  /**
   * Build RouteObject array
   */
  private buildRouteObjects(pages: PageConfig[]): RouteObject[] {
    return pages.map((page): RouteObject => ({
      path: page.path,
      element: this.createRouteElement(page),
      children: page.children 
        ? this.buildRouteObjects(page.children as PageConfig[])
        : undefined,
    }));
  }
  
  /**
   * Create route element
   * 
   * Route guards, error boundaries, etc. can be added here.
   */
  private createRouteElement(_page: PageConfig): React.ReactNode {
    // Note: Returning JSX here requires compilation support
    // In actual implementation, createElement may be needed
    // Component rendering is handled by Host layer's RouterProvider
    return null;
  }
  
  /**
   * Create router instance
   */
  private createRouter(routes: RouteObject[]): RouterInstance {
    const { type, basename, initialEntries } = this.options;
    
    if (type === 'memory') {
      return createMemoryRouter(routes, {
        basename,
        initialEntries,
      });
    }
    
    return createBrowserRouter(routes, {
      basename,
    });
  }
  
  /**
   * Get router instance
   * 
   * Returns the react-router Router instance for use with RouterProvider.
   */
  getRouter(): RouterInstance | null {
    return this.router;
  }
  
  /**
   * Navigate by PageId
   * 
   * This is the core method for NavigationCapability implementation.
   * 
   * @param pageId - Page ID
   * @param params - Route parameters
   * @param options - Navigation options
   * @returns Whether navigation was successful
   */
  navigateToPage(
    pageId: string,
    params?: Record<string, string>,
    options?: NavigateOptions
  ): boolean {
    if (!this.router) {
      return false;
    }
    
    const path = this.pageIdToPath.get(pageId);
    if (!path) {
      return false;
    }
    
    // Replace path parameters
    let url = path;
    if (params) {
      for (const [key, value] of Object.entries(params)) {
        url = url.replace(`:${key}`, encodeURIComponent(value));
      }
    }
    
    // Execute navigation
    this.router.navigate(url, {
      replace: options?.replace,
      state: options?.state,
    });
    
    return true;
  }
  
  /**
   * Navigate by URL path
   * 
   * For internal Host use only, plugins should not call this method.
   */
  navigateToPath(path: string, options?: NavigateOptions): void {
    if (!this.router) {
      return;
    }
    
    this.router.navigate(path, {
      replace: options?.replace,
      state: options?.state,
    });
  }
  
  /**
   * Go back
   */
  goBack(): void {
    if (!this.router) {
      return;
    }
    this.router.navigate(-1);
  }
  
  /**
   * Go forward
   */
  goForward(): void {
    if (!this.router) {
      return;
    }
    this.router.navigate(1);
  }
  
  /**
   * Get current location
   */
  getCurrentLocation(): Location | null {
    return this.router?.state.location ?? null;
  }
  
  /**
   * Get current PageId
   */
  getCurrentPageId(): string | null {
    const location = this.getCurrentLocation();
    if (!location) {
      return null;
    }
    return this.pathToPageId.get(location.pathname) ?? null;
  }
  
  /**
   * Get URL path by PageId
   */
  getPathByPageId(pageId: string): string | undefined {
    return this.pageIdToPath.get(pageId);
  }
  
  /**
   * Get PageId by URL path
   */
  getPageIdByPath(path: string): string | undefined {
    return this.pathToPageId.get(path);
  }
  
  /**
   * Check if PageId is registered
   */
  hasPage(pageId: string): boolean {
    return this.pageIdToPath.has(pageId);
  }
  
  /**
   * Get all registered page IDs
   */
  getAllPageIds(): string[] {
    return Array.from(this.pageIdToPath.keys());
  }
  
  /**
   * Add route change listener
   * 
   * @param listener - Listener function
   * @returns Unsubscribe function
   */
  onRouteChange(listener: RouteChangeListener): () => void {
    this.listeners.add(listener);
    return () => {
      this.listeners.delete(listener);
    };
  }
  
  /**
   * Destroy the adapter
   */
  destroy(): void {
    this.listeners.clear();
    this.pageIdToPath.clear();
    this.pathToPageId.clear();
    this.registeredPages.length = 0;
    this.router = null;
  }
}
